name: Auto Release on Tag 

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: 

jobs:
  call-shared:
    permissions:
      contents: write
    uses: yt-dlp-plugins/.github/.github/workflows/python_release.yml@main
